### ISSUE TITLE
Error after app closed

### ISSUE THREAD

**Issue by spalenzuela** [Mauricio07/SendSMS#2]
I am trying to send an SMS in background but when closing the app I receive this error:

05-25 14:18:51.218 32645 32711 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke v
irtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference, null)
05-25 14:18:51.218 32645 32711 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
05-25 14:18:51.218 32645 32711 E flutter : #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
05-25 14:18:51.218 32645 32711 E flutter : <asynchronous suspension>
05-25 14:18:51.218 32645 32711 E flutter : #2      Sendsms.onGetPermission (package:sendsms/sendsms.dart:23:27)
05-25 14:18:51.218 32645 32711 E flutter : #3      SMS.sendEmergencySMS (package:myapp/services/sms.dart:27:21)
05-25 14:18:51.218 32645 32711 E flutter : <asynchronous suspension>
05-25 14:18:51.218 32645 32711 E flutter : #4      _initScheduleNotification (package:myapp/main.dart:89:21)
05-25 14:18:51.218 32645 32711 E flutter : <asynchronous suspension>
05-25 14:18:51.218 32645 32711 E flutter : #5      backgroundFetchHeadlessTask (package:myapp/main.dart:190:42)
05-25 14:18:51.218 32645 32711 E flutter : <asynchronous suspension>
05-25 14:18:51.218 32645 32711 E flutter : #6      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:619:15
)
05-25 14:18:51.218 32645 32711 E flutter : #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
05-25 14:18:51.218 32645 32711 E flutter : #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.
dart:370:54)
05-25 14:18:51.218 32645 32711 E flutter : #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
05-25 14:18:51.218 32645 32711 E flutter : <asynchronous suspension>
05-25 14:18:51.218 32645 32711 E flutter : #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
05-25 14:18:51.218 32645 32711 E flutter : #11     _rootRun (dart:async/zone.dart:1126:13)
05-25 14:18:51.218 32645 32711 E flutter : #12     _CustomZone.run (dart:async/zone.dart:1023:19)
05-25 14:18:51.218 32645 32711 E flutter : #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
05-25 14:18:51.218 32645 32711 E flutter : #14     _invoke3 (dart:ui/hooks.dart:302:10)
05-25 14:18:51.218 32645 32711 E flutter : #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)

**Comment by Mauricio07** [comment]
hi, please,
could you tell me your code to help you

**Comment by Mauricio07** [comment]
you are sending a null instead of the phone number, tell me if your problem was solved

**Comment by spalenzuela** [comment]
> you are sending a null instead of the phone number, tell me if your problem was solved

Resolved! It was a permission problem

**Comment by Marcosirala** [comment]
> 



> hi, please, could you tell me your code to help you

**Comment by Mauricio07** [comment]
Hi, I'm sorry I don't understand your question, my code is in git you can
download it
